description = "Compile AppArmor profiles"

[check]
paths = [
    "/etc/apparmor.d"
]

[skip]
chroot = true

[deps]
after = [
    "systemd-reexec"
]

[[bins]]
task = "Compiling and Reloading AppArmor profiles"
bin = "/usr/sbin/aa-lsm-hook"
