description = "Update gconf database"

[check]
paths = [
    "/etc/gconf/schemas",
    "/etc/gconf/gconf.xml.defaults",
    "/usr/share/gconf/schemas"
]

[deps]
after = [
    "glib2"
]

[env]
GCONF_CONFIG_SOURCE = "xml:merged:/etc/gconf/gconf.xml.defaults"

[[bins]]
task = "Preparing gconf tree"
bin = "mkdir"
args = [
    "-p",
    "/etc/gconf/gconf.xml.defaults"
]

[[bins]]
task = "Rebuilding gconf database"
bin = "/usr/bin/gconftool-2"
args = [
    "--makefile-install-rule"
]

[[remove]]
paths = [
    "/etc/gconf/gconf.xml.defaults/*"
]
exclude = [
    "*.xml"
]

