description = "Compile glib-schemas"

[[bins]]
task = "Compiling glib-schemas"
bin = "/usr/bin/glib-compile-schemas"
args = [
    "***"
]

    [bins.replace]
    paths = [
        "/usr/share/glib-2.0/schemas"
    ]

[check]
paths = [
    "/usr/share/glib-2.0/schemas"
]
