description = "Update GTK2 input module cache"

[check]
paths = [
    "/usr/lib/gtk-2.0/2.*/immodules"
]

[[bins]]
task = "Updating GTK2 input module cache"
bin = "/usr/bin/gtk-query-immodules-2.0"
args = [
    "--update-cache"
]
