description = "Update GTK3 input module cache"

[[bins]]
task = "Updating GTK3 input module cache"
bin = "/usr/bin/gtk-query-immodules-3.0"
args = [
    "--update-cache"
]

[check]
paths = [
    "/usr/lib/gtk-3.0/3.*/immodules"
]
