description = "Update hardware database"

[check]
paths = [
    "/usr/lib/udev/hwdb.d",
    "/etc/udev/hwdb.d"
]

[deps]
after = [
    "systemd-reexec"
]

[[bins]]
task = "Updating hardware database"
bin = "/usr/bin/systemd-hwdb"
args = [
    "update"
]
