description = "Update dynamic library cache"

[[bins]]
task = "Updating dynamic library cache"
bin = "/sbin/ldconfig"
args = [
    "-X"
]

[check]
paths = [
    "/usr/lib64",
    "/usr/lib",
    "/lib64",
    "/lib",
    "/usr/share/ld.so.conf.d"
]
