description = "Update graphical driver configuration"

[deps]
after = [
    "depmod"
]

[[bins]]
task = "Updating graphical driver configuration"
bin = "/usr/bin/linux-driver-management"
args = [
    "configure",
    "gpu"
]
