description = "Populate Mono certificates"

[[bins]]
task = "Populating Mono certificates"
bin = "/usr/bin/cert-sync"
args = [
    "--quiet",
    "***"
]

    [bins.replace]
    paths = [
        "/etc/ssl/certs/ca-certificates.crt"
    ]

[check]
paths = [
    "/etc/ssl/certs"
]

[skip]
chroot = true
