description = "Create OpenSSH host key"

[check]
paths = [
    "/etc/ssh"
]

[skip]
paths = [
    "/etc/ssh/ssh_host_rsa_key",
    "/etc/ssh/ssh_host_dsa_key"
]

[[bins]]
task = "Creating OpenSSH host key"
bin = "/usr/bin/ssh-keygen"
args = [
    "-q", 
    "-t", "rsa", 
    "-f", "/etc/ssh/ssh_host_rsa_key", 
    "-C", 
    "-N"
]
