description = "Register QoL migration"

[check]
paths = [
    "/usr/sbin/qol-assist",
    "/usr/lib/systemd/system/qol-assist-migration.service"
]

[skip]
chroot = true
live = true

[deps]
after = [
    "systemd-reload"
]

[[bins]]
task = "Registering QoL migration on next boot"
bin = "/usr/sbin/qol-assist"
args = [
    "trigger"
]
