description = "Re-execute systemd"

[[bins]]
task = "Re-executing systemd"
bin = "/usr/bin/systemctl"
args = [
    "daemon-reexec"
]

[check]
paths = [
    "/etc/systemd/system",
    "/usr/lib/systemd/system"
]

[skip]
chroot = true
live = true
