description = "Restart vendor-enabled systemd socket units"

[[bins]]
task = "Restarting socket units"
bin = "/usr/bin/systemctl"
args = [
    "restart",
    "sockets.target"
]

[check]
paths = [
    "/usr/lib/systemd/system/sockets.target.wants"
]

[skip]
chroot = true
live = true
