description = "Reload systemd configuration"

[check]
paths = [
    "/etc/systemd/system",
    "/usr/lib/systemd/system"
]

[skip]
chroot = true

[deps]
after = [
    "systemd-reexec",
    "sysusers",
    "tmpfiles"
]

[[bins]]
task = "Reloading systemd configuration"
bin = "/usr/bin/systemctl"
args = [
    "daemon-reload"
]
