description = "Restart vendor-enabled systemd socket units"

[check]
paths = [
    "/usr/lib/systemd/system/sockets.target.wants"
]

[skip]
chroot = true
live = true

[deps]
after = [
    "systemd-reexec"
]

[[bins]]
task = "Restarting socket units"
bin = "/usr/bin/systemctl"
args = [
    "restart",
    "sockets.target"
]
