description = "Update desktop database"

[check]
paths = [
    "/usr/share/applications"
]

[[bins]]
task = "Updating desktop database"
bin = "/usr/bin/update-desktop-database"
args = [
    "-q",
    "***"
]

    [bins.replace]
    paths = [
        "/usr/share/applications"
    ]
