description = "Restart VirtualBox services"

[check]
paths = [
    "/usr/lib/systemd/system/vboxdrv.service"
]

[skip]
chroot = true
live = true

[deps]
after = [
    "clr-boot-manager"
]

[[bins]]
task = "Restarting VirtualBox services"
bin = "/usr/bin/systemctl"
args = [
    "restart",
    "vboxdrv.service"
]
